import {
  Activity, Archive, ArrowDown, ArrowRight, ArrowUp, Ban,
  Bell, BellOff, Bookmark, Box, Bug, Calendar,
  Camera, ChartBar, ChartPie, Check, CircleAlert, CircleCheck,
  CircleHelp, CircleX, Clock, Cloud, CloudOff, CloudRain,
  Code, Coffee, Coins, Compass, Copy, Cpu,
  CreditCard, Database, DollarSign, Download, ExternalLink, Eye,
  EyeOff, File, FileCode, FileText, Filter, Flag,
  Flame, Folder, FolderOpen, Gauge, GitBranch, GitCommitHorizontal,
  GitMerge, GitPullRequest, Globe, Grid3x3, HardDrive, Heart,
  History, Hourglass, Image, Inbox, Info, Key,
  Layers, Leaf, Lightbulb, Link, List, Lock,
  Mail, MapPin, MessageSquare, Mic, Minus, Moon,
  Music, Package, Pause, Pin, Play, Plus,
  Receipt, RefreshCw, Rocket, Save, Search, Send,
  Server, Settings, Share2, Shield, SkipForward, SlidersHorizontal,
  Sparkles, Square, Star, Sun, Tag, Target,
  Terminal, ThumbsDown, ThumbsUp, Timer, Trash2, TrendingDown,
  TrendingUp, TriangleAlert, Unlock, Upload, User, UserCheck,
  Users, Volume2, Wallet, Wand2, Wrench, X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import type { WidgetIcon } from '@/types/surface';

/**
 * The drawing for each name the agent may use.
 *
 * A total record over `WidgetIcon`, so a name added to the vocabulary without a
 * drawing here is a compile error rather than a hole in a panel — the same
 * property the widget registry has, for the same reason.
 *
 * Imported by name rather than reached through the library's dynamic index, so
 * the bundler keeps these hundred and drops the other five thousand.
 */
export const WIDGET_ICON_COMPONENTS: Record<WidgetIcon, LucideIcon> = {
  'check': Check,
  'x': X,
  'triangle-alert': TriangleAlert,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  'info': Info,
  'circle-help': CircleHelp,
  'ban': Ban,
  'clock': Clock,
  'hourglass': Hourglass,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-right': ArrowRight,
  'minus': Minus,
  'plus': Plus,
  'code': Code,
  'terminal': Terminal,
  'git-branch': GitBranch,
  'git-commit-horizontal': GitCommitHorizontal,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  'bug': Bug,
  'package': Package,
  'box': Box,
  'layers': Layers,
  'database': Database,
  'server': Server,
  'cpu': Cpu,
  'hard-drive': HardDrive,
  'cloud': Cloud,
  'cloud-off': CloudOff,
  'file': File,
  'file-text': FileText,
  'file-code': FileCode,
  'folder': Folder,
  'folder-open': FolderOpen,
  'save': Save,
  'download': Download,
  'upload': Upload,
  'trash2': Trash2,
  'copy': Copy,
  'mail': Mail,
  'message-square': MessageSquare,
  'bell': Bell,
  'bell-off': BellOff,
  'send': Send,
  'share2': Share2,
  'user': User,
  'users': Users,
  'user-check': UserCheck,
  'heart': Heart,
  'star': Star,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'receipt': Receipt,
  'wallet': Wallet,
  'coins': Coins,
  'calendar': Calendar,
  'timer': Timer,
  'history': History,
  'refresh-cw': RefreshCw,
  'play': Play,
  'pause': Pause,
  'square': Square,
  'skip-forward': SkipForward,
  'globe': Globe,
  'link': Link,
  'search': Search,
  'filter': Filter,
  'eye': Eye,
  'eye-off': EyeOff,
  'lock': Lock,
  'unlock': Unlock,
  'key': Key,
  'shield': Shield,
  'zap': Zap,
  'flame': Flame,
  'sparkles': Sparkles,
  'wand2': Wand2,
  'lightbulb': Lightbulb,
  'target': Target,
  'flag': Flag,
  'map-pin': MapPin,
  'compass': Compass,
  'gauge': Gauge,
  'activity': Activity,
  'chart-bar': ChartBar,
  'chart-pie': ChartPie,
  'list': List,
  'grid3x3': Grid3x3,
  'settings': Settings,
  'sliders-horizontal': SlidersHorizontal,
  'wrench': Wrench,
  'rocket': Rocket,
  'coffee': Coffee,
  'moon': Moon,
  'sun': Sun,
  'cloud-rain': CloudRain,
  'leaf': Leaf,
  'music': Music,
  'image': Image,
  'camera': Camera,
  'mic': Mic,
  'volume2': Volume2,
  'bookmark': Bookmark,
  'pin': Pin,
  'tag': Tag,
  'inbox': Inbox,
  'archive': Archive,
  'external-link': ExternalLink,
};
